<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/qlc-apis/pedidosPessoa/db_PROC_BUSCA_PEDIDO" name="db_PROC_BUSCA_PEDIDO-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="db_PROC_BUSCA_PEDIDO.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/qlc-apis/pedidosPessoa/db_PROC_BUSCA_PEDIDO"/>
    <wsdl:binding name="db_PROC_BUSCA_PEDIDO_ptt-binding" type="db:db_PROC_BUSCA_PEDIDO_ptt" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/qlc-apis/pedidosPessoa/db_PROC_BUSCA_PEDIDO">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="db_PROC_BUSCA_PEDIDO">
            <soap:operation soapAction="db_PROC_BUSCA_PEDIDO"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>